/**
 * rubato app registry — the list of apps/dirs you can jump to by name or alias.
 *
 * Stored in ~/.rubato/apps.json, generated by `rubato-scan` and freely edited by
 * the user (aliases, titles, and API metadata like gitlab/quay/rancher fields).
 * Unknown fields are preserved across re-scans, so user additions are safe.
 */

import { readdir, readFile, stat } from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';
import { $ } from 'bun';
import { logger } from 'cwip';
import type { AppAiConfig, AppApi, CommandType, KnownApiName } from './appApis';
import { APPS_FILE, expandPath } from './config';

export type { AppApi, CommandType, Db, JenkinsAppApi, JenkinsEnvConfig } from './appApis';

/** A user-associated shortcut URL for an app (jenkins/quay/openshift/etc.). */
export interface AppLink {
  /** Link text shown in the UI. */
  text: string;
  /** URL opened in a new tab on click. */
  href: string;
}

/**
 * One registry entry. Two layers in one type, by design:
 *  1. A **named path** you jump to / run commands against — `name`, `aliases`,
 *     `absolutePath`, `group`. True of every entry; this is what `goto`/`gotab`
 *     act on, and the path may be a repo dir, a plain dir, or a single file.
 *  2. **App metadata** layered on when the path is a real repo/service — `apis`,
 *     `db`, `ai`, and the scan-derived `managed`/`repoName`/`packageJsonName`.
 *
 * "app" is the friendly umbrella for the common case (most entries are repos);
 * the bare dir/file case is the deliberate escape hatch (e.g. `gotab zs` → ~/.zshrc).
 */
export interface AppConfig {
  /** User-facing title. Defaults to the directory name; never overwritten by scans. */
  name: string;
  /**
   * Absolute path to the app. Usually a repo directory, but a hand-added entry
   * can point at any directory or a single file (e.g. ~/.zshrc) — `goto` cd's to
   * the containing dir and `gotab` opens the file in the editor.
   */
  absolutePath: string;
  /** Directory basename (derived). */
  dirName: string;
  /** Repo name from the git remote, falling back to dirName (derived). */
  repoName?: string;
  /** `name` field from package.json, if present (derived). */
  packageJsonName?: string;
  /** Parent path relative to its scan root, or null when at the root (derived). */
  group: string | null;
  /** Extra words the user associates with this app for matching. */
  aliases: string[];
  /**
   * Databases the app uses (informational; shown as tech tags). Common values come
   * from the `Db` enum (mongodb/postgres/mysql/mssql/sqlite/redis) but any custom
   * string is allowed — an app may use a db we didn't anticipate. Seed it from the
   * package.json drivers via the Apps page "Detect" button, then edit freely.
   */
  db?: string[];
  /**
   * Free-form tech tags the user adds beyond what `db`/`apis`/`cloneUrl` already
   * imply (e.g. "harness", "rancher", or anything bespoke). User-owned, preserved
   * across re-scans. The displayed tag set is `effectiveAppTags(app)`.
   */
  tags?: string[];
  /** Command categories this app opts out of (e.g. ["git"] to protect the repo). */
  ignoreCommandTypes?: CommandType[];
  /** Per-app API integrations (jenkins, gitlab, quay, ...). */
  apis?: AppApi[];
  /** Per-app AI / "ask about your repo" overrides (provider, model, retriever, globs). */
  ai?: AppAiConfig;
  /**
   * User-associated shortcut URLs (jenkins/quay/openshift/harness/rancher/…),
   * surfaced in the UI as click-to-open-in-new-tab links and available to plug
   * into automations.
   */
  links?: AppLink[];
  /**
   * The git clone URL (origin remote) for repo apps — filled by config-fill from
   * the repo's `origin`, or set when an app is cloned through rubato. Lets the UI
   * offer "clone elsewhere"/re-clone and feeds clone automations.
   */
  cloneUrl?: string;
  /** True for scan-discovered repos; false/absent for hand-added entries. */
  managed?: boolean;
  /**
   * Pin an entry so `rubato-scan` keeps its hands off it: even if a repo is
   * rediscovered at this path, scan won't refresh its derived fields or take it
   * over as managed. Use it to freeze an in-root repo, or alongside a hand-added
   * out-of-root entry (e.g. ~/.claude) you want protected regardless of where it
   * lives. Hand-added (unmanaged) entries are already immune to scan's missing/
   * removed reconciliation; `pinned` additionally blocks the rediscovery refresh.
   */
  pinned?: boolean;
  /** Set by scan when a managed path has disappeared from disk. */
  missing?: boolean;
  /** Any other user-added metadata is preserved as-is across re-scans. */
  [key: string]: unknown;
}

/** Map a known API name to its config type for the typed `getAppApi` overloads. */
type ApiByName = {
  jenkins: import('./appApis').JenkinsAppApi;
  gitlab: import('./appApis').GitlabAppApi;
  quay: import('./appApis').QuayAppApi;
  splunk: import('./appApis').SplunkAppApi;
  openshift: import('./appApis').OpenshiftAppApi;
};

/** Find an app's config for a given API integration, typed by name. */
export function getAppApi<N extends KnownApiName>(app: AppConfig, name: N): ApiByName[N] | undefined;
export function getAppApi(app: AppConfig, name: string): AppApi | undefined;
export function getAppApi(app: AppConfig, name: string): AppApi | undefined {
  return app.apis?.find((api) => api.name === name);
}

/**
 * Resolve an app's OpenShift namespace from its `openshift` API config: a
 * per-environment `namespaces[env]` wins when an env is given, else the single
 * `namespace`. Pure; returns undefined when unconfigured.
 */
export function resolveAppNamespace(app: AppConfig, env?: string): string | undefined {
  const oc = getAppApi(app, 'openshift');
  if (!oc) return undefined;
  if (env && oc.namespaces?.[env]) return oc.namespaces[env];
  return oc.namespace;
}

/** True if the app has opted out of the given command category. */
export function ignoresCommand(app: AppConfig, type: CommandType): boolean {
  return app.ignoreCommandTypes?.includes(type) ?? false;
}

// Parsed registry is reused across calls and only re-read when apps.json changes
// (keyed on mtime+size), so the per-request loadApps() calls don't re-parse a
// potentially large file each time. saveApps clears it; a scan/hand edit changes
// the mtime and is picked up automatically.
let appsCache: { mtimeMs: number; size: number; value: AppConfig[] } | null = null;

/** Drop the in-process app-registry cache (after an out-of-band write, or in tests). */
export function clearAppsCache(): void {
  appsCache = null;
}

export async function loadApps(): Promise<AppConfig[]> {
  let st: { mtimeMs: number; size: number };
  try {
    st = await stat(APPS_FILE);
  } catch {
    return []; // no registry yet
  }
  if (appsCache && appsCache.mtimeMs === st.mtimeMs && appsCache.size === st.size) {
    return appsCache.value.slice(); // shallow copy: callers may sort/filter the result
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(await readFile(APPS_FILE, 'utf8'));
  } catch (err) {
    // A hand-edited registry with a typo shouldn't crash every command.
    console.warn(
      `[rubato] ${APPS_FILE} is not valid JSON (${err instanceof Error ? err.message : err}); ` +
        'treating the registry as empty — run rubato-scan to rebuild it.',
    );
    return [];
  }
  // Drop malformed rows (missing name/absolutePath) so one bad entry can't make
  // a downstream command pass undefined to the filesystem.
  const value = Array.isArray(parsed)
    ? (parsed as AppConfig[]).filter(
        (a) => a && typeof a.name === 'string' && typeof a.absolutePath === 'string' && a.absolutePath.trim() !== '',
      )
    : [];
  appsCache = { mtimeMs: st.mtimeMs, size: st.size, value };
  return value.slice();
}

export async function saveApps(apps: AppConfig[]): Promise<void> {
  await Bun.write(APPS_FILE, `${JSON.stringify(apps, null, 2)}\n`);
  clearAppsCache();
}

/**
 * Coerce user-supplied links to clean { text, href } pairs: trim both, drop any
 * with a blank href, and default the text to the href when only a URL was given.
 * Defensive — `links` is user/HTTP input.
 */
export function normalizeAppLinks(raw: unknown): AppLink[] {
  if (!Array.isArray(raw)) return [];
  const out: AppLink[] = [];
  for (const item of raw) {
    const href = typeof (item as AppLink)?.href === 'string' ? (item as AppLink).href.trim() : '';
    if (!href) continue;
    const textRaw = typeof (item as AppLink)?.text === 'string' ? (item as AppLink).text.trim() : '';
    out.push({ text: textRaw || href, href });
  }
  return out;
}

/**
 * Set (or clear) an app's shortcut links by name, persisting to apps.json. Empty
 * → the field is removed entirely. Returns the updated app, or null if no app of
 * that name exists.
 */
export async function setAppLinks(name: string, rawLinks: unknown): Promise<AppConfig | null> {
  const apps = await loadApps();
  const app = apps.find((a) => a.name === name);
  if (!app) return null;
  const links = normalizeAppLinks(rawLinks);
  if (links.length) app.links = links;
  else delete app.links;
  await saveApps(apps);
  return app;
}

/** Service api names that double as tech tags (jenkins/gitlab/quay/splunk/openshift/…). */
function vcsHost(url: string | undefined): string | undefined {
  if (!url) return undefined;
  const u = url.toLowerCase();
  if (u.includes('github')) return 'github';
  if (u.includes('gitlab')) return 'gitlab';
  if (u.includes('bitbucket')) return 'bitbucket';
  return undefined;
}

/**
 * The tech tags shown for an app — the union of: its `db` list, the names of its
 * `apis` integrations (jenkins/gitlab/quay/openshift/splunk, and any custom api
 * name like rancher/harness), the VCS host inferred from `cloneUrl`, and the
 * user's free-form `tags`. Deduped + lowercased + sorted, so the UI just renders.
 */
export function effectiveAppTags(app: AppConfig): string[] {
  const tags = new Set<string>();
  const add = (v: unknown) => {
    if (typeof v === 'string' && v.trim()) tags.add(v.trim().toLowerCase());
  };
  for (const d of app.db ?? []) add(d);
  for (const api of app.apis ?? []) add(api?.name);
  add(vcsHost(app.cloneUrl));
  for (const t of app.tags ?? []) add(t);
  return [...tags].sort();
}

/** Coerce user/HTTP input into a clean, deduped, lowercased, non-empty string list. */
export function normalizeStringList(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of raw) {
    if (typeof item !== 'string') continue;
    const v = item.trim().toLowerCase();
    if (!v || seen.has(v)) continue;
    seen.add(v);
    out.push(v);
  }
  return out;
}

/** Set (or clear, when empty) an app's `db` list by name. Returns the updated app or null. */
export async function setAppDb(name: string, rawDb: unknown): Promise<AppConfig | null> {
  const apps = await loadApps();
  const app = apps.find((a) => a.name === name);
  if (!app) return null;
  const db = normalizeStringList(rawDb);
  if (db.length) app.db = db;
  else delete app.db;
  await saveApps(apps);
  return app;
}

/** Set (or clear, when empty) an app's free-form tech `tags` by name. */
export async function setAppTags(name: string, rawTags: unknown): Promise<AppConfig | null> {
  const apps = await loadApps();
  const app = apps.find((a) => a.name === name);
  if (!app) return null;
  const tags = normalizeStringList(rawTags);
  if (tags.length) app.tags = tags;
  else delete app.tags;
  await saveApps(apps);
  return app;
}

/**
 * Resolve the registered app that owns a filesystem path: an exact `absolutePath`
 * match, else the nearest ancestor app dir the path lives under (deepest wins).
 * Used to attribute a saved command's `cwd` to an app for its tech tags.
 */
export function findAppByPath(absPath: string, apps: AppConfig[]): AppConfig | null {
  const target = absPath.replace(/\/+$/, '');
  if (!target) return null;
  let best: AppConfig | null = null;
  for (const app of apps) {
    const ap = app.absolutePath.replace(/\/+$/, '');
    if (ap === target) return app;
    if (target.startsWith(`${ap}/`) && (!best || ap.length > best.absolutePath.replace(/\/+$/, '').length)) {
      best = app;
    }
  }
  return best;
}

/**
 * Remove an app from the registry by exact name, persisting to apps.json. Only the
 * registry entry is dropped — files on disk are left untouched (this unregisters
 * the app, it does not delete the repo). Returns the removed app, or null if no
 * app of that name exists.
 */
export async function removeApp(name: string): Promise<AppConfig | null> {
  const apps = await loadApps();
  const idx = apps.findIndex((a) => a.name === name);
  if (idx === -1) return null;
  const [removed] = apps.splice(idx, 1);
  await saveApps(apps);
  return removed;
}

/** The fields a scan derives on its own; everything else is user-supplied. */
const DERIVED_KEYS = new Set([
  'name',
  'absolutePath',
  'dirName',
  'repoName',
  'packageJsonName',
  'group',
  'aliases',
  'managed',
  'missing',
]);

/**
 * True if an entry carries anything the user added by hand — a custom title, any
 * aliases, or extra metadata (gitlab/quay/rancher/...). Purely-derived entries
 * (everything scan-generated, untouched) return false, so scan can safely drop
 * them when they vanish from disk instead of leaving stale cruft behind.
 */
export function hasUserData(app: AppConfig): boolean {
  if (app.aliases?.length) return true;
  if (app.name !== app.dirName) return true;
  return Object.keys(app).some((k) => !DERIVED_KEYS.has(k));
}

/** Every string by which a query can match this app (deduped, non-empty). */
export function matchKeys(app: AppConfig): string[] {
  // these can have dups when backups copies of the same repo are in multiple dirs:
  // app.name, app.dirName, app.repoName, app.packageJsonName
  const raw = [app.name, app.dirName, app.repoName, app.packageJsonName, ...(app.aliases ?? [])];
  const seen = new Set<string>();
  const keys: string[] = [];
  for (const k of raw) {
    if (typeof k !== 'string') continue;
    const trimmed = k.trim();
    if (!trimmed) continue;
    const lc = trimmed.toLowerCase();
    if (seen.has(lc)) continue; // collapse name===dirName===repoName, etc.
    seen.add(lc);
    keys.push(trimmed);
  }
  return keys;
}

/** Where a single match key on an app comes from, with a path to open. */
export interface KeySource {
  /** The field that produced the key, e.g. "packageJsonName". */
  field: string;
  /** Human label for output, e.g. "package.json name". */
  label: string;
  /**
   * Absolute path to inspect for this key: the app's package.json for a package
   * name, the repo dir for a dir/repo name, or the registry file for the
   * title/aliases. Printed bare so terminals linkify it (cmd+click).
   */
  path: string;
}

/** Match-key source fields in display priority (most specific/surprising first). */
const KEY_SOURCE_FIELDS: { field: keyof AppConfig | 'aliases'; label: string }[] = [
  { field: 'packageJsonName', label: 'package.json name' },
  { field: 'aliases', label: 'alias' },
  { field: 'repoName', label: 'repo name (git remote)' },
  { field: 'dirName', label: 'directory name' },
  { field: 'name', label: 'name' },
];

/**
 * Every field on `app` whose value equals `key` (case-insensitive), each with a
 * concrete path to open. Drives rubato-scan's "which file claims this key"
 * conflict output: e.g. a package name resolves to that repo's package.json so
 * you can jump straight to the offending file. Ordered most-specific first.
 */
export function keySources(app: AppConfig, key: string): KeySource[] {
  const lc = key.trim().toLowerCase();
  const sources: KeySource[] = [];
  for (const { field, label } of KEY_SOURCE_FIELDS) {
    const matches =
      field === 'aliases'
        ? (app.aliases ?? []).some((a) => typeof a === 'string' && a.trim().toLowerCase() === lc)
        : typeof app[field] === 'string' && (app[field] as string).trim().toLowerCase() === lc;
    if (!matches) continue;
    const path =
      field === 'packageJsonName'
        ? join(app.absolutePath, 'package.json')
        : field === 'repoName' || field === 'dirName'
          ? app.absolutePath
          : APPS_FILE;
    sources.push({ field: String(field), label, path });
  }
  return sources;
}

/** One claimant in a registry conflict. */
export interface ConflictApp {
  name: string;
  /** Absolute path to the app's directory. */
  path: string;
  /** For match-key conflicts: where this app's clashing key comes from. */
  sources?: KeySource[];
}

/** A structured registry conflict (see `validateAppsDetailed`). */
export type Conflict =
  | { kind: 'duplicate-name'; key: string; apps: [ConflictApp, ConflictApp] }
  | { kind: 'duplicate-path'; key: string; apps: [ConflictApp, ConflictApp] }
  | { kind: 'match-key'; key: string; apps: [ConflictApp, ConflictApp] };

/** The one-line human string for a conflict (also used to dedupe). */
export function conflictString(c: Conflict): string {
  switch (c.kind) {
    case 'duplicate-name':
      return `Duplicate name "${c.key}": ${c.apps[0].path} and ${c.apps[1].path}`;
    case 'duplicate-path':
      return `Duplicate absolutePath "${c.key}" (names "${c.apps[0].name}" and "${c.apps[1].name}")`;
    case 'match-key':
      return `Match key "${c.key}" is claimed by both "${c.apps[0].name}" and "${c.apps[1].name}"`;
  }
}

/**
 * Validate that the registry can be matched unambiguously, returning structured
 * conflicts that name *where* each clashing value comes from:
 *   - no two apps share a name (case-insensitive)
 *   - no two apps share an absolutePath
 *   - no match key (name/dir/repo/package/alias) belongs to more than one app
 * Empty when valid. `validateApps` formats these to strings.
 */
export function validateAppsDetailed(apps: AppConfig[]): Conflict[] {
  const conflicts: Conflict[] = [];
  const seen = new Set<string>();
  const push = (c: Conflict) => {
    const sig = conflictString(c);
    if (seen.has(sig)) return;
    seen.add(sig);
    conflicts.push(c);
  };

  const byName = new Map<string, AppConfig>();
  const byPath = new Map<string, AppConfig>();
  const byKey = new Map<string, AppConfig>();

  for (const app of apps) {
    const nameLc = app.name?.toLowerCase() ?? '';
    const nameOwner = byName.get(nameLc);
    if (nameOwner) {
      push({
        kind: 'duplicate-name',
        key: app.name,
        apps: [
          { name: nameOwner.name, path: nameOwner.absolutePath },
          { name: app.name, path: app.absolutePath },
        ],
      });
    } else {
      byName.set(nameLc, app);
    }

    const pathOwner = byPath.get(app.absolutePath);
    if (pathOwner) {
      push({
        kind: 'duplicate-path',
        key: app.absolutePath,
        apps: [
          { name: pathOwner.name, path: pathOwner.absolutePath },
          { name: app.name, path: app.absolutePath },
        ],
      });
    } else {
      byPath.set(app.absolutePath, app);
    }

    for (const key of matchKeys(app)) {
      const lc = key.toLowerCase();
      const owner = byKey.get(lc);
      if (owner && owner !== app) {
        push({
          kind: 'match-key',
          key,
          apps: [
            { name: owner.name, path: owner.absolutePath, sources: keySources(owner, key) },
            { name: app.name, path: app.absolutePath, sources: keySources(app, key) },
          ],
        });
      } else if (!owner) {
        byKey.set(lc, app);
      }
    }
  }
  return conflicts;
}

/**
 * Human-readable registry problems (empty when valid). Thin formatter over
 * `validateAppsDetailed`; use that directly when you need the source paths.
 */
export function validateApps(apps: AppConfig[]): string[] {
  return validateAppsDetailed(apps).map(conflictString);
}

/**
 * The directory `goto` should cd into for an app. For a normal directory entry
 * that's the path itself; for a file entry (e.g. ~/.zshrc) it's the containing
 * directory, since you can't cd into a file. `gotab` opens the path as-is.
 */
export async function gotoTarget(absolutePath: string): Promise<string> {
  try {
    const info = await stat(absolutePath);
    return info.isDirectory() ? absolutePath : dirname(absolutePath);
  } catch {
    return absolutePath; // let the shell's cd surface a clear error
  }
}

/** Every app whose match keys include the query (case-insensitive). */
export function findMatches(query: string, apps: AppConfig[]): AppConfig[] {
  const q = query.trim().toLowerCase();
  return apps.filter((app) => matchKeys(app).some((k) => k.toLowerCase() === q));
}

/**
 * Resolve a query to a single registered app, erroring to stderr + exiting on
 * ambiguity or a missing path. Returns null (no error) when nothing matches, so
 * callers can decide what a zero-match means. The integrity check is per-query:
 * a messy registry elsewhere won't block an unambiguous lookup, but a query that
 * hits two apps errors with the candidates listed.
 */
function pickMatch(query: string, apps: AppConfig[]): AppConfig | null {
  const matches = findMatches(query, apps);

  if (matches.length === 0) return null;
  if (matches.length > 1) {
    // find a match by alias
    const bestMatch = matches.find((m) => m.aliases.includes(query));
    if (bestMatch) {
      return bestMatch;
    }

    const list = matches.map((m) => `  - ${m.name}  (${m.absolutePath})`).join('\n');
    logger.warn(
      `rubato: "${query}" is ambiguous — it matches:\n${list}\nRemove the shared key or rename one in ${APPS_FILE}. Using first match`,
    );
  }

  const app = matches[0];
  if (app.missing) {
    throw new Error(`rubato: "${app.name}" no longer exists at ${app.absolutePath}.`);
  }
  return app;
}

/**
 * Resolve a query to a single app for a command. Throws with an actionable
 * message when the query is unresolved or ambiguous.
 */
export async function resolveApp(query: string): Promise<AppConfig> {
  const app = pickMatch(query, await loadApps());
  if (!app) {
    throw new Error(`rubato: no app matches "${query}". Run \`rubato-scan\` or edit ${APPS_FILE}.`);
  }
  return app;
}

/** A jump target for `goto`/`gotab`: either a registered app or a bare path. */
export interface GotoTarget {
  /** Display name — the app's name, or the path's basename for a raw path. */
  name: string;
  /** Absolute path to jump to / open. */
  absolutePath: string;
}

/**
 * Resolve a query for `goto`/`gotab` without exiting on a zero-match. A
 * registered app wins; with zero app matches, a query that is itself a real
 * existing file or dir is accepted as a one-off target — so `goto ./some/dir`
 * or `gotab ~/notes.md` work without registering them first. Returns null when
 * nothing matches and the query isn't a real path, leaving the caller to decide
 * what that means (e.g. `gotab` opens the registry so you can add it). Ambiguity
 * and missing apps throw (via `pickMatch`).
 */
export async function tryResolveAppOrPath(query: string): Promise<GotoTarget | null> {
  const app = pickMatch(query, await loadApps());
  if (app) return { name: app.name, absolutePath: app.absolutePath };

  // No app matched — accept a real filesystem path passed directly.
  const path = expandPath(query);
  try {
    await stat(path);
    return { name: basename(path), absolutePath: path };
  } catch {
    return null;
  }
}

/**
 * Like `tryResolveAppOrPath`, but throws when nothing matches. Callers that
 * need a clean CLI error message should catch and print `err.message`.
 */
export async function resolveAppOrPath(query: string): Promise<GotoTarget> {
  const target = await tryResolveAppOrPath(query);
  if (target) return target;
  throw new Error(
    `rubato: no app matches "${query}", and it isn't a file or dir. Run \`rubato-scan\` or edit ${APPS_FILE}.`,
  );
}

/** Derive repoName from a repo's git remote, falling back to the given default. */
export async function readRepoName(repoPath: string, fallback: string): Promise<string> {
  const r = await $`git -C ${repoPath} config --get remote.origin.url`.nothrow().quiet();
  if (r.exitCode === 0) {
    const url = r.stdout.toString().trim();
    const base = url
      .split(/[/:]/)
      .pop()
      ?.replace(/\.git$/, '');
    if (base) return base;
  }
  return fallback;
}

/** Read the `name` field from a repo's package.json, if any. */
export async function readPackageName(repoPath: string): Promise<string | undefined> {
  const pkg = Bun.file(`${repoPath}/package.json`);
  if (!(await pkg.exists())) return undefined;
  try {
    const json = JSON.parse(await pkg.text());
    return typeof json.name === 'string' ? json.name : undefined;
  } catch {
    return undefined;
  }
}

/** Result of browsing a directory for the folder-picker UI. */
export interface BrowseDirResult {
  /** Resolved absolute path that was listed. */
  path: string;
  /** Subdirectory names (not paths) within `path`, sorted alphabetically. Hidden dirs (starting with `.`) are excluded. */
  dirs: string[];
  /** User's home directory, for the "Home" shortcut. */
  home: string;
}

/**
 * List subdirectories of `dir` for the folder-picker UI. Expands `~` and relative
 * paths. Hidden entries (`.foo`) are excluded so the list stays navigable.
 */
export async function browseDir(dir: string): Promise<BrowseDirResult> {
  const home = expandPath('~');
  const resolved = resolve(expandPath(dir || home));
  let entries: string[];
  try {
    const raw = await readdir(resolved, { withFileTypes: true });
    entries = raw
      .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
      .map((e) => e.name)
      .sort((a, b) => a.localeCompare(b));
  } catch {
    entries = [];
  }
  return { path: resolved, dirs: entries, home };
}

/** Parse a repo's package.json, or undefined if absent/unreadable. */
export async function readPackageJson(repoPath: string): Promise<Record<string, unknown> | undefined> {
  const pkg = Bun.file(`${repoPath}/package.json`);
  if (!(await pkg.exists())) return undefined;
  try {
    const json = JSON.parse(await pkg.text());
    return json && typeof json === 'object' ? (json as Record<string, unknown>) : undefined;
  } catch {
    return undefined;
  }
}
