/**
 * Pure codegen: turn a saved Automation into a standalone @playwright/test spec
 * that any app can drop into its own e2e suite (no rubato dependency at runtime).
 *
 * The generated locators MUST behave like a real run, so the per-kind mapping
 * here is kept in lockstep with resolveLocator() in src/scripts/browser-host.mjs
 * and the action mapping with execAction() there. When you change how a target
 * resolves or an action runs in the host, mirror it here (and in locator.ts).
 *
 * Variable interpolation is preserved by translation rather than evaluation:
 *   ${scraped.NAME}  → a local `const` captured from an earlier scrape step
 *   ${OTHER}         → process.env.OTHER (env/secret, the consumer supplies it)
 * so an exported spec is self-contained and reads the way a hand-written test would.
 */

import type { Automation, Condition, LeafAction, Step, StepParams, Target } from '../shared/automation';

export interface ExportOptions {
  /** Title for the generated test() block. Defaults to the automation name. */
  testName?: string;
  /**
   * Module to import `test`/`expect` from. Defaults to "@playwright/test".
   * Point it at a consumer's fixtures module (e.g. "../fixtures") to inherit that
   * app's extended `test` — auth overrides, custom contexts — instead of the bare
   * Playwright one. The module must re-export both `test` and `expect`.
   */
  testModule?: string;
}

/** Render an Automation as the text of a `*.spec.ts` Playwright test file. */
export function automationToSpec(automation: Automation, opts: ExportOptions = {}): string {
  // Multi-tab automations need a mutable "active page" variable (the fixture's
  // `page` is const) plus the `context` fixture to open/list tabs.
  const multiTab = usesMultiTab(automation);
  const ctx: GenCtx = {
    scrapeIdents: new Map(),
    usedIdents: new Set(),
    needsFs: false,
    root: multiTab ? 'active' : 'page',
    tabCount: 0,
  };
  const body: string[] = [];

  // An automation may open with an implicit goto (startUrl), mirroring the runner.
  if (automation.startUrl) body.push(`await ${ctx.root}.goto(${jsString(automation.startUrl, ctx)});`);
  for (const step of automation.steps) body.push(...emitStep(step, ctx, 1));
  if (multiTab) body.unshift(`let active = page;`);

  const testName = opts.testName ?? automation.name;
  const imports = [`import { expect, test } from ${jsLiteral(opts.testModule ?? '@playwright/test')};`];
  if (ctx.needsFs) imports.push(`import { writeFile } from "node:fs/promises";`);

  const lines: string[] = [
    `// Generated by rubato from automation "${automation.name}" (id: ${automation.id}).`,
    `// Edit the automation in the rubato UI and re-export rather than hand-editing here.`,
  ];
  const { usesEnv, inlinesSecret } = scanSecrets(automation);
  if (usesEnv) {
    lines.push(`// Uses environment variables (process.env.*) — set them before running this test.`);
  }
  if (inlinesSecret) {
    lines.push(`// NOTE: a secret value is inlined below as plain text — prefer an env variable for committed specs.`);
  }
  lines.push('', ...imports, '');
  lines.push(`test(${jsLiteral(testName)}, async ({ ${multiTab ? 'page, context' : 'page'} }) => {`);
  lines.push(...body.map((l) => (l ? `  ${l}` : l)));
  lines.push(`});`, '');
  return lines.join('\n');
}

interface GenCtx {
  /** scrape saveAs name → the JS identifier holding its captured value. */
  scrapeIdents: Map<string, string>;
  usedIdents: Set<string>;
  /** A saveFile step was seen, so the spec needs node:fs/promises. */
  needsFs: boolean;
  /** The variable locators/page-calls are rooted at — "page", or "active" for multi-tab specs. */
  root: string;
  /** How many tabs `newTab` has opened so far (names them tab1, tab2, …). */
  tabCount: number;
}

/** Does any step open/switch/close a tab? Determines the active-page indirection. */
function usesMultiTab(automation: Automation): boolean {
  const TAB = new Set(['newTab', 'switchTab', 'closeTab']);
  const walk = (steps: Step[]): boolean =>
    steps.some((s) => TAB.has(s.action) || walk(s.thenSteps ?? []) || walk(s.elseSteps ?? []));
  return walk(automation.steps);
}

const INDENT = '  ';

/** Emit one step (recursing into `if` branches) as indented source lines. */
function emitStep(step: Step, ctx: GenCtx, depth: number): string[] {
  const pad = INDENT.repeat(depth - 1);
  const lines = step.note ? [`${pad}// ${step.note.replace(/\r?\n/g, ' ')}`] : [];

  if (step.action === 'if') {
    lines.push(...emitIf(step, ctx, depth));
    return lines;
  }

  const stmts = emitLeaf(step.action, step.target, step.params ?? {}, step.options?.timeout, ctx);
  // An optional step records-and-continues on failure; mirror with try/catch.
  if (step.options?.optional) {
    lines.push(`${pad}try {`);
    for (const s of stmts) lines.push(`${pad}${INDENT}${s}`);
    lines.push(`${pad}} catch {`, `${pad}${INDENT}// optional step — ignore failure`, `${pad}}`);
  } else {
    for (const s of stmts) lines.push(`${pad}${s}`);
  }
  return lines;
}

function emitIf(step: Step, ctx: GenCtx, depth: number): string[] {
  const pad = INDENT.repeat(depth - 1);
  const cond = step.condition ? conditionExpr(step.condition, ctx) : 'false';
  const out = [`${pad}if (${cond}) {`];
  for (const s of step.thenSteps ?? []) out.push(...emitStep(s, ctx, depth + 1));
  if (step.elseSteps?.length) {
    out.push(`${pad}} else {`);
    for (const s of step.elseSteps) out.push(...emitStep(s, ctx, depth + 1));
  }
  out.push(`${pad}}`);
  return out;
}

/** A condition for an `if` step → a boolean JS expression. */
function conditionExpr(cond: Condition, ctx: GenCtx): string {
  switch (cond.kind) {
    case 'url-matches':
      return urlMatchExpr(cond.value ?? '', ctx.root);
    case 'selector-visible':
      return cond.target ? `await ${locator(cond.target, ctx.root)}.first().isVisible()` : 'false';
    case 'selector-hidden':
      return cond.target ? `!(await ${locator(cond.target, ctx.root)}.first().isVisible())` : 'false';
    default:
      return 'false';
  }
}

/** A single leaf action → one or more JS statements. */
function emitLeaf(
  action: LeafAction,
  target: Target | undefined,
  p: StepParams,
  timeout: number | undefined,
  ctx: GenCtx,
): string[] {
  const root = ctx.root;
  const loc = target ? locator(target, root) : null;
  const opt = timeout ? `{ timeout: ${timeout} }` : '';
  const withOpt = (...args: string[]) => [...args.filter(Boolean), opt].filter(Boolean).join(', ');

  switch (action) {
    case 'goto':
      return [`await ${root}.goto(${withOpt(jsString(p.url ?? p.value ?? '', ctx))});`];
    case 'click':
      return [`await ${loc}.first().click(${opt});`];
    case 'hover':
      return [`await ${loc}.first().hover(${opt});`];
    case 'fill':
      return [`await ${loc}.first().fill(${withOpt(valueExpr(p, ctx))});`];
    case 'select':
      return [`await ${loc}.first().selectOption(${withOpt(valueExpr(p, ctx))});`];
    case 'check':
      return [`await ${loc}.first().check(${opt});`];
    case 'uncheck':
      return [`await ${loc}.first().uncheck(${opt});`];
    case 'setFiles':
      return [`await ${loc}.first().setInputFiles(${withOpt(filesExpr(p, ctx))});`];
    case 'press':
      return loc
        ? [`await ${loc}.first().press(${withOpt(valueExpr(p, ctx, 'Enter'))});`]
        : [`await ${root}.keyboard.press(${valueExpr(p, ctx, 'Enter')});`];
    case 'dialog': {
      const accept = p.dialogAction !== 'dismiss';
      if (!accept) return [`${root}.once("dialog", (d) => d.dismiss());`];
      const arg = p.value || p.valueMode === 'env' ? valueExpr(p, ctx) : '';
      return [`${root}.once("dialog", (d) => d.accept(${arg}));`];
    }
    case 'newTab':
      return emitNewTab(p, ctx);
    case 'switchTab':
      return [`active = context.pages()[${p.count ?? 0}];`];
    case 'closeTab':
      return [`await active.close();`, `active = context.pages()[context.pages().length - 1];`];
    case 'waitFor':
      return [emitWaitFor(loc, p, timeout, root)];
    case 'expectText': {
      const matcher = target?.exact ? 'toHaveText' : 'toContainText';
      return [`await expect(${loc}.first()).${matcher}(${withOpt(valueExpr(p, ctx))});`];
    }
    case 'expectUrl':
      return [`await expect(${root}).toHaveURL(${urlPattern(p.value ?? '')}${opt ? `, ${opt}` : ''});`];
    case 'expectTitle':
      return [
        `await expect(${root}).toHaveTitle(${titlePattern(p.value ?? '', target?.exact)}${opt ? `, ${opt}` : ''});`,
      ];
    case 'expectVisible':
      return [`await expect(${loc}.first()).toBeVisible(${opt});`];
    case 'expectHidden':
      return [`await expect(${loc}.first()).toBeHidden(${opt});`];
    case 'expectEnabled':
      return [`await expect(${loc}.first()).toBeEnabled(${opt});`];
    case 'expectDisabled':
      return [`await expect(${loc}.first()).toBeDisabled(${opt});`];
    case 'expectValue':
      return [`await expect(${loc}.first()).toHaveValue(${withOpt(expectedValueArg(p.value ?? '', ctx))});`];
    case 'expectAttribute':
      return [
        `await expect(${loc}.first()).toHaveAttribute(${withOpt(jsLiteral(p.attr ?? ''), expectedValueArg(p.value ?? '', ctx))});`,
      ];
    case 'expectCount':
      return [`await expect(${loc}).toHaveCount(${withOpt(String(p.count ?? 0))});`];
    case 'scrape':
      return [emitScrape(loc ?? `${root}.locator('body')`, target, p, ctx)];
    case 'screenshot':
      return [
        p.path
          ? `await ${root}.screenshot({ path: ${jsString(p.path, ctx)}, fullPage: true });`
          : `await ${root}.screenshot({ fullPage: true });`,
      ];
    case 'snapshot': {
      // No single @playwright/test analog — capture both an image and the HTML,
      // mirroring the runner's snapshot step.
      ctx.needsFs = true;
      const stem = p.value
        ? p.value.replace(/[^A-Za-z0-9._-]+/g, '_').replace(/^_+|_+$/g, '') || 'snapshot'
        : 'snapshot';
      return [
        `await ${root}.screenshot({ path: ${jsLiteral(`${stem}.png`)}, fullPage: true });`,
        `await writeFile(${jsLiteral(`${stem}.html`)}, await ${root}.content());`,
      ];
    }
    case 'saveFile':
      return emitSaveFile(p, ctx);
    default:
      return [`// unsupported action: ${action}`];
  }
}

/** newTab: open a fresh page, optionally navigate, and make it active. */
function emitNewTab(p: StepParams, ctx: GenCtx): string[] {
  const ident = `tab${++ctx.tabCount}`;
  ctx.usedIdents.add(ident);
  const lines = [`const ${ident} = await context.newPage();`];
  if (p.url) lines.push(`await ${ident}.goto(${jsString(p.url, ctx)});`);
  lines.push(`active = ${ident};`);
  return lines;
}

/** setFiles paths → a single string arg, or an array when several were given. */
function filesExpr(p: StepParams, ctx: GenCtx): string {
  const parts = (p.value ?? '')
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (parts.length <= 1) return jsString(parts[0] ?? '', ctx);
  return `[${parts.map((s) => jsString(s, ctx)).join(', ')}]`;
}

/** An expected value for toHaveValue/toHaveAttribute: a `/regex/` → RegExp, else a string. */
function expectedValueArg(value: string, ctx: GenCtx): string {
  const re = parseRegex(value);
  if (re)
    return re.flags
      ? `new RegExp(${jsLiteral(re.source)}, ${jsLiteral(re.flags)})`
      : `new RegExp(${jsLiteral(re.source)})`;
  return jsString(value, ctx);
}

function emitWaitFor(loc: string | null, p: StepParams, timeout: number | undefined, root: string): string {
  const t = timeout ? `, { timeout: ${timeout} }` : '';
  switch (p.waitKind) {
    case 'ms':
      return `await ${root}.waitForTimeout(${p.ms ?? 1000});`;
    case 'load':
      return `await ${root}.waitForLoadState("load"${t});`;
    case 'networkidle':
      return `await ${root}.waitForLoadState("networkidle"${t});`;
    case 'visible':
      return `await ${loc}.first().waitFor({ state: "visible"${t ? `, timeout: ${timeout}` : ''} });`;
    case 'hidden':
      return `await ${loc}.first().waitFor({ state: "hidden"${t ? `, timeout: ${timeout}` : ''} });`;
    default:
      return `await ${root}.waitForTimeout(${p.ms ?? 500});`;
  }
}

function emitScrape(loc: string, _target: Target | undefined, p: StepParams, ctx: GenCtx): string {
  const ident = scrapeIdent(p.saveAs ?? 'scraped', ctx);
  const read = p.attr
    ? `(await ${loc}.first().getAttribute(${jsLiteral(p.attr)})) ?? ""`
    : `await ${loc}.first().innerText()`;
  return `const ${ident} = ${read};`;
}

function emitSaveFile(p: StepParams, ctx: GenCtx): string[] {
  ctx.needsFs = true;
  // Blank value ⇒ the runner dumps the whole scrape bag; export the captured vars.
  const content = p.value || p.valueMode === 'env' ? valueExpr(p, ctx) : scrapeBagExpr(ctx);
  const path = p.path ? jsString(p.path, ctx) : `"automation-output.txt"`;
  return [`await writeFile(${path}, ${content});`];
}

/**
 * The JS expression for a step's `value`, honoring its mode:
 *  - "env": read the named env var — process.env[NAME] (the secure path; nothing
 *    sensitive is baked into the spec).
 *  - "secret"/text: inline the value as a string (a "secret" literal is the user's
 *    own — masked in the builder, but it lands in the exported file as written).
 */
function valueExpr(p: StepParams, ctx: GenCtx, fallback = ''): string {
  if (p.valueMode === 'env') return `process.env[${jsLiteral((p.value ?? '').trim())}] ?? ""`;
  return jsString(p.value ?? fallback, ctx);
}

// ── locators (mirror resolveLocator in browser-host.mjs) ─────────────────────

/** A Target → a chained Playwright locator expression rooted at `root` ("page" or "active"). */
function locator(target: Target, root: string): string {
  const base = target.container ? locator(target.container, root) : root;
  let expr: string;
  switch (target.kind) {
    case 'role':
      expr = target.name
        ? `${base}.getByRole(${jsLiteral(target.value)}, { name: ${jsLiteral(target.name)}${target.exact ? ', exact: true' : ''} })`
        : `${base}.getByRole(${jsLiteral(target.value)})`;
      break;
    case 'testid':
      expr = `${base}.getByTestId(${jsLiteral(target.value)})`;
      break;
    case 'text':
      expr = `${base}.getByText(${jsLiteral(target.value)}${target.exact ? ', { exact: true }' : ''})`;
      break;
    case 'label':
      expr = `${base}.getByLabel(${jsLiteral(target.value)}${target.exact ? ', { exact: true }' : ''})`;
      break;
    case 'placeholder':
      expr = `${base}.getByPlaceholder(${jsLiteral(target.value)}${target.exact ? ', { exact: true }' : ''})`;
      break;
    case 'id':
      expr = `${base}.locator(${jsLiteral(`#${cssEscape(target.value)}`)})`;
      break;
    case 'class':
      expr = `${base}.locator(${jsLiteral(`.${cssEscape(target.value)}`)})`;
      break;
    case 'href':
      expr = `${base}.locator(${jsLiteral(`a[href="${target.value.replace(/"/g, '\\"')}"]`)})`;
      break;
    case 'css':
      expr = `${base}.locator(${jsLiteral(target.value)})`;
      break;
    default:
      expr = `${base}.locator(${jsLiteral(target.value)})`;
  }
  if (typeof target.nth === 'number') expr += `.nth(${target.nth})`;
  return expr;
}

function cssEscape(s: string): string {
  return s.replace(/([ !"#$%&'()*+,./:;<=>?@[\]^`{|}~])/g, '\\$1');
}

// ── url / title matching (mirror urlMatches in browser-host.mjs) ─────────────

/** Parse a rubato `/regex/flags` or substring pattern into {source, flags} or null. */
function parseRegex(pattern: string): { source: string; flags: string } | null {
  const m = pattern.match(/^\/(.*)\/([a-z]*)$/);
  return m ? { source: m[1], flags: m[2] } : null;
}

/** A url pattern → a RegExp/string argument for expect(page).toHaveURL(). */
function urlPattern(pattern: string): string {
  const re = parseRegex(pattern);
  if (re)
    return re.flags
      ? `new RegExp(${jsLiteral(re.source)}, ${jsLiteral(re.flags)})`
      : `new RegExp(${jsLiteral(re.source)})`;
  // Substring match — the runner uses url.includes(pattern); a contains-regex matches that.
  return `new RegExp(${jsLiteral(escapeRegExp(pattern))})`;
}

/** A url pattern → a boolean expression over <root>.url() (for `if` conditions). */
function urlMatchExpr(pattern: string, root: string): string {
  const re = parseRegex(pattern);
  if (re) return `new RegExp(${jsLiteral(re.source)}${re.flags ? `, ${jsLiteral(re.flags)}` : ''}).test(${root}.url())`;
  return `${root}.url().includes(${jsLiteral(pattern)})`;
}

function titlePattern(value: string, exact: boolean | undefined): string {
  // exact ⇒ string equality; otherwise a contains-regex (mirrors title.includes()).
  return exact ? jsLiteral(value) : `new RegExp(${jsLiteral(escapeRegExp(value))})`;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ── variable interpolation ───────────────────────────────────────────────────

const VAR = /\$\{([^}]+)\}/g;

/**
 * A rubato interpolated string → a JS string expression. When the value contains
 * no `${...}`, emit a plain string literal; otherwise emit a template literal that
 * splices in `process.env.X` / captured scrape identifiers, preserving semantics.
 */
function jsString(value: string, ctx: GenCtx): string {
  VAR.lastIndex = 0;
  if (!VAR.test(value)) return jsLiteral(value);
  VAR.lastIndex = 0;
  const tpl = value
    .replace(/[\\`]/g, '\\$&')
    .replace(/\$(?!\{)/g, '\\$') // escape a bare $ that isn't starting a ${...}
    .replace(VAR, (_m, raw) => {
      const key = String(raw).trim();
      if (key.startsWith('scraped.')) {
        const name = key.slice('scraped.'.length);
        return `\${${scrapeIdent(name, ctx, /*declareIfMissing*/ false)}}`;
      }
      return `\${process.env[${jsLiteral(key)}] ?? ""}`;
    });
  return `\`${tpl}\``;
}

/** An expression that builds the whole scrape bag as JSON (saveFile with no value). */
function scrapeBagExpr(ctx: GenCtx): string {
  if (ctx.scrapeIdents.size === 0) return `JSON.stringify({}, null, 2)`;
  const entries = [...ctx.scrapeIdents.entries()].map(([name, id]) => `${jsLiteral(name)}: ${id}`).join(', ');
  return `JSON.stringify({ ${entries} }, null, 2)`;
}

/**
 * Map a scrape `saveAs` name to a stable, valid, unique JS identifier. On first
 * sight of a name (declaration) it reserves the identifier; later references
 * reuse it. References to an unknown scrape name fall back to "" rather than a
 * reference error, matching the runner's empty-string behavior for missing vars.
 */
function scrapeIdent(name: string, ctx: GenCtx, declareIfMissing = true): string {
  const existing = ctx.scrapeIdents.get(name);
  if (existing) return existing;
  if (!declareIfMissing) return `""`;
  let base = name.replace(/[^A-Za-z0-9_$]/g, '_');
  if (!/^[A-Za-z_$]/.test(base)) base = `_${base}`;
  let ident = base;
  let n = 2;
  while (ctx.usedIdents.has(ident)) ident = `${base}${n++}`;
  ctx.usedIdents.add(ident);
  ctx.scrapeIdents.set(name, ident);
  return ident;
}

/** Whether the spec reads env vars (${VAR} or a valueMode "env" step), and whether
 *  any "secret" literal is inlined verbatim — both drive header notes. */
function scanSecrets(automation: Automation): { usesEnv: boolean; inlinesSecret: boolean } {
  let usesEnv = false;
  let inlinesSecret = false;
  const scan = (s: string | undefined) => {
    if (!s) return;
    for (const m of s.matchAll(VAR)) if (!m[1].trim().startsWith('scraped.')) usesEnv = true;
  };
  const walk = (steps: Step[]) => {
    for (const step of steps) {
      scan(step.params?.url);
      scan(step.params?.value);
      scan(step.params?.path);
      if (step.params?.valueMode === 'env') usesEnv = true;
      // A "secret" literal with no ${VAR} lands in the file as plain text.
      if (step.params?.valueMode === 'secret' && step.params.value && !step.params.value.includes('${')) {
        inlinesSecret = true;
      }
      if (step.thenSteps) walk(step.thenSteps);
      if (step.elseSteps) walk(step.elseSteps);
    }
  };
  scan(automation.startUrl);
  walk(automation.steps);
  return { usesEnv, inlinesSecret };
}

/** A JS string literal (always double-quoted, safely escaped). */
function jsLiteral(s: string): string {
  return JSON.stringify(s);
}
