import { describe, expect, test } from 'bun:test';
import type { Automation, Step } from '../shared/automation';
import { automationToSpec } from './exportSpec';

function build(steps: Step[], extra: Partial<Automation> = {}): Automation {
  return {
    id: 'demo',
    name: 'Demo flow',
    steps,
    createdAt: 0,
    updatedAt: 0,
    ...extra,
  };
}

describe('automationToSpec', () => {
  test('emits a @playwright/test scaffold with a named test', () => {
    const spec = automationToSpec(build([]));
    expect(spec).toContain(`import { expect, test } from "@playwright/test";`);
    expect(spec).toContain(`test("Demo flow", async ({ page }) => {`);
    expect(spec).toContain(`// Generated by rubato`);
    expect(spec.trimEnd().endsWith('});')).toBe(true);
  });

  test('startUrl becomes an implicit opening goto', () => {
    const spec = automationToSpec(build([], { startUrl: 'https://example.com' }));
    expect(spec).toContain(`await page.goto("https://example.com");`);
  });

  test('maps each locator kind to the matching Playwright getter', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'click', target: { kind: 'role', value: 'button', name: 'Save' } },
        { id: 'b', action: 'click', target: { kind: 'role', value: 'link', name: 'Home', exact: true } },
        { id: 'c', action: 'click', target: { kind: 'testid', value: 'submit' } },
        { id: 'd', action: 'click', target: { kind: 'text', value: 'Hello', exact: true } },
        { id: 'e', action: 'click', target: { kind: 'label', value: 'Email' } },
        { id: 'f', action: 'click', target: { kind: 'placeholder', value: 'Search' } },
        { id: 'g', action: 'click', target: { kind: 'id', value: 'main' } },
        { id: 'h', action: 'click', target: { kind: 'class', value: 'btn' } },
        { id: 'i', action: 'click', target: { kind: 'href', value: '/about' } },
        { id: 'j', action: 'click', target: { kind: 'css', value: '.x > .y' } },
      ]),
    );
    expect(spec).toContain(`page.getByRole("button", { name: "Save" }).first().click();`);
    expect(spec).toContain(`page.getByRole("link", { name: "Home", exact: true }).first().click();`);
    expect(spec).toContain(`page.getByTestId("submit").first().click();`);
    expect(spec).toContain(`page.getByText("Hello", { exact: true }).first().click();`);
    expect(spec).toContain(`page.getByLabel("Email").first().click();`);
    expect(spec).toContain(`page.getByPlaceholder("Search").first().click();`);
    expect(spec).toContain(`page.locator("#main").first().click();`);
    expect(spec).toContain(`page.locator(".btn").first().click();`);
    expect(spec).toContain(`page.locator("a[href=\\"/about\\"]").first().click();`);
    expect(spec).toContain(`page.locator(".x > .y").first().click();`);
  });

  test('container scopes the locator and nth selects a match', () => {
    const spec = automationToSpec(
      build([
        {
          id: 'a',
          action: 'click',
          target: {
            kind: 'role',
            value: 'button',
            name: 'Delete',
            nth: 2,
            container: { kind: 'testid', value: 'row' },
          },
        },
      ]),
    );
    expect(spec).toContain(`page.getByTestId("row").getByRole("button", { name: "Delete" }).nth(2).first().click();`);
  });

  test('fill/select/check/press map to their actions', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'fill', target: { kind: 'id', value: 'email' }, params: { value: 'x@y.z' } },
        { id: 'b', action: 'select', target: { kind: 'id', value: 'country' }, params: { value: 'US' } },
        { id: 'c', action: 'check', target: { kind: 'id', value: 'tos' } },
        { id: 'd', action: 'uncheck', target: { kind: 'id', value: 'promo' } },
        { id: 'e', action: 'press', target: { kind: 'id', value: 'email' }, params: { value: 'Enter' } },
        { id: 'f', action: 'press', params: { value: 'Escape' } },
      ]),
    );
    expect(spec).toContain(`page.locator("#email").first().fill("x@y.z");`);
    expect(spec).toContain(`page.locator("#country").first().selectOption("US");`);
    expect(spec).toContain(`page.locator("#tos").first().check();`);
    expect(spec).toContain(`page.locator("#promo").first().uncheck();`);
    expect(spec).toContain(`page.locator("#email").first().press("Enter");`);
    expect(spec).toContain(`await page.keyboard.press("Escape");`);
  });

  test('expect actions map to expect() matchers', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'expectText', target: { kind: 'id', value: 'msg' }, params: { value: 'Saved' } },
        {
          id: 'b',
          action: 'expectText',
          target: { kind: 'id', value: 'msg', exact: true },
          params: { value: 'Saved' },
        },
        { id: 'c', action: 'expectVisible', target: { kind: 'testid', value: 'modal' } },
        { id: 'd', action: 'expectCount', target: { kind: 'class', value: 'row' }, params: { count: 3 } },
        { id: 'e', action: 'expectUrl', params: { value: '/dashboard' } },
        { id: 'f', action: 'expectUrl', params: { value: '/users/\\d+/i' } },
        { id: 'g', action: 'expectTitle', params: { value: 'Home' } },
      ]),
    );
    expect(spec).toContain(`await expect(page.locator("#msg").first()).toContainText("Saved");`);
    expect(spec).toContain(`await expect(page.locator("#msg").first()).toHaveText("Saved");`);
    expect(spec).toContain(`await expect(page.getByTestId("modal").first()).toBeVisible();`);
    expect(spec).toContain(`await expect(page.locator(".row")).toHaveCount(3);`);
    expect(spec).toContain(`await expect(page).toHaveURL(new RegExp("/dashboard"));`);
    expect(spec).toContain(`await expect(page).toHaveURL(new RegExp("users/\\\\d+", "i"));`);
    expect(spec).toContain(`await expect(page).toHaveTitle(new RegExp("Home"));`);
  });

  test('waitFor variants', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'waitFor', params: { waitKind: 'ms', ms: 2000 } },
        { id: 'b', action: 'waitFor', params: { waitKind: 'networkidle' } },
        { id: 'c', action: 'waitFor', params: { waitKind: 'load' } },
        { id: 'd', action: 'waitFor', target: { kind: 'testid', value: 'spin' }, params: { waitKind: 'hidden' } },
      ]),
    );
    expect(spec).toContain(`await page.waitForTimeout(2000);`);
    expect(spec).toContain(`await page.waitForLoadState("networkidle");`);
    expect(spec).toContain(`await page.waitForLoadState("load");`);
    expect(spec).toContain(`await page.getByTestId("spin").first().waitFor({ state: "hidden" });`);
  });

  test('scrape declares a const and later steps reference it', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'scrape', target: { kind: 'id', value: 'total' }, params: { saveAs: 'total' } },
        { id: 'b', action: 'scrape', target: { kind: 'id', value: 'link' }, params: { saveAs: 'href', attr: 'href' } },
        {
          id: 'c',
          action: 'fill',
          target: { kind: 'id', value: 'out' },
          params: { value: 'Total is ${scraped.total}' },
        },
      ]),
    );
    expect(spec).toContain(`const total = await page.locator("#total").first().innerText();`);
    expect(spec).toContain(`const href = (await page.locator("#link").first().getAttribute("href")) ?? "";`);
    expect(spec).toContain('page.locator("#out").first().fill(`Total is ${total}`);');
  });

  test('env vars become process.env lookups and add a header note', () => {
    const spec = automationToSpec(
      build([{ id: 'a', action: 'fill', target: { kind: 'id', value: 'pw' }, params: { value: '${PASSWORD}' } }]),
    );
    expect(spec).toContain('page.locator("#pw").first().fill(`${process.env["PASSWORD"] ?? ""}`);');
    expect(spec).toContain('// Uses environment variables');
  });

  test('optional steps are wrapped in try/catch', () => {
    const spec = automationToSpec(
      build([{ id: 'a', action: 'click', target: { kind: 'id', value: 'x' }, options: { optional: true } }]),
    );
    expect(spec).toContain('try {');
    expect(spec).toContain(`page.locator("#x").first().click();`);
    expect(spec).toContain('// optional step — ignore failure');
  });

  test('per-step timeout is threaded into the call', () => {
    const spec = automationToSpec(
      build([{ id: 'a', action: 'click', target: { kind: 'id', value: 'x' }, options: { timeout: 5000 } }]),
    );
    expect(spec).toContain(`page.locator("#x").first().click({ timeout: 5000 });`);
  });

  test('if steps become real branches', () => {
    const spec = automationToSpec(
      build([
        {
          id: 'a',
          action: 'if',
          condition: { kind: 'selector-visible', target: { kind: 'testid', value: 'cookie' } },
          thenSteps: [{ id: 't', action: 'click', target: { kind: 'testid', value: 'accept' } }],
          elseSteps: [{ id: 'e', action: 'click', target: { kind: 'testid', value: 'decline' } }],
        },
      ]),
    );
    expect(spec).toContain(`if (await page.getByTestId("cookie").first().isVisible()) {`);
    expect(spec).toContain(`page.getByTestId("accept").first().click();`);
    expect(spec).toContain(`} else {`);
    expect(spec).toContain(`page.getByTestId("decline").first().click();`);
  });

  test('saveFile imports fs and writes content', () => {
    const withValue = automationToSpec(
      build([
        { id: 's', action: 'scrape', target: { kind: 'id', value: 'v' }, params: { saveAs: 'x' } },
        { id: 'a', action: 'saveFile', params: { value: 'hi ${scraped.x}', path: 'out.txt' } },
      ]),
    );
    expect(withValue).toContain(`import { writeFile } from "node:fs/promises";`);
    expect(withValue).toContain('await writeFile("out.txt", `hi ${x}`);');

    const bag = automationToSpec(
      build([
        { id: 'a', action: 'scrape', target: { kind: 'id', value: 'n' }, params: { saveAs: 'name' } },
        { id: 'b', action: 'saveFile', params: {} },
      ]),
    );
    expect(bag).toContain(`await writeFile("automation-output.txt", JSON.stringify({ "name": name }, null, 2));`);
  });

  test('screenshot with and without a path', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'screenshot', params: { path: 'shot.png' } },
        { id: 'b', action: 'screenshot', params: {} },
      ]),
    );
    expect(spec).toContain(`await page.screenshot({ path: "shot.png", fullPage: true });`);
    expect(spec).toContain(`await page.screenshot({ fullPage: true });`);
  });

  test('snapshot captures both an image and the HTML, using the label as the filename', () => {
    const spec = automationToSpec(build([{ id: 'a', action: 'snapshot', params: { value: 'after login' } }]));
    expect(spec).toContain(`import { writeFile } from "node:fs/promises";`);
    expect(spec).toContain(`await page.screenshot({ path: "after_login.png", fullPage: true });`);
    expect(spec).toContain(`await writeFile("after_login.html", await page.content());`);
  });

  test('snapshot without a label falls back to a default filename', () => {
    const spec = automationToSpec(build([{ id: 'a', action: 'snapshot', params: {} }]));
    expect(spec).toContain(`await page.screenshot({ path: "snapshot.png", fullPage: true });`);
    expect(spec).toContain(`await writeFile("snapshot.html", await page.content());`);
  });

  test("valueMode 'env' reads from process.env[name]", () => {
    const spec = automationToSpec(
      build([
        {
          id: 'a',
          action: 'fill',
          target: { kind: 'id', value: 'pw' },
          params: { value: 'LOGIN_PW', valueMode: 'env' },
        },
      ]),
    );
    expect(spec).toContain(`page.locator("#pw").first().fill(process.env["LOGIN_PW"] ?? "");`);
    expect(spec).toContain('// Uses environment variables');
  });

  test("valueMode 'secret' inlines the literal and warns in the header", () => {
    const spec = automationToSpec(
      build([
        {
          id: 'a',
          action: 'fill',
          target: { kind: 'id', value: 'pw' },
          params: { value: 's3cr3t', valueMode: 'secret' },
        },
      ]),
    );
    expect(spec).toContain(`page.locator("#pw").first().fill("s3cr3t");`);
    expect(spec).toContain('// NOTE: a secret value is inlined');
  });

  test("valueMode 'secret' with a ${VAR} reference is not flagged as inlined", () => {
    const spec = automationToSpec(
      build([
        {
          id: 'a',
          action: 'fill',
          target: { kind: 'id', value: 'pw' },
          params: { value: '${PW}', valueMode: 'secret' },
        },
      ]),
    );
    expect(spec).toContain('page.locator("#pw").first().fill(`${process.env["PW"] ?? ""}`);');
    expect(spec).not.toContain('// NOTE: a secret value is inlined');
  });

  test('hover, setFiles (single + multiple), and dialog map to their actions', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'hover', target: { kind: 'testid', value: 'menu' } },
        { id: 'b', action: 'setFiles', target: { kind: 'id', value: 'file' }, params: { value: '/tmp/a.csv' } },
        {
          id: 'c',
          action: 'setFiles',
          target: { kind: 'id', value: 'files' },
          params: { value: '/tmp/a.csv, /tmp/b.csv' },
        },
        { id: 'd', action: 'dialog', params: { dialogAction: 'accept', value: 'yes' } },
        { id: 'e', action: 'dialog', params: { dialogAction: 'dismiss' } },
        { id: 'f', action: 'dialog', params: {} }, // default = accept, no prompt
      ]),
    );
    expect(spec).toContain(`await page.getByTestId("menu").first().hover();`);
    expect(spec).toContain(`await page.locator("#file").first().setInputFiles("/tmp/a.csv");`);
    expect(spec).toContain(`await page.locator("#files").first().setInputFiles(["/tmp/a.csv", "/tmp/b.csv"]);`);
    expect(spec).toContain(`page.once("dialog", (d) => d.accept("yes"));`);
    expect(spec).toContain(`page.once("dialog", (d) => d.dismiss());`);
    expect(spec).toContain(`page.once("dialog", (d) => d.accept());`);
  });

  test('new expect actions map to their matchers (incl. /regex/ values)', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'expectHidden', target: { kind: 'testid', value: 'spin' } },
        { id: 'b', action: 'expectEnabled', target: { kind: 'id', value: 'save' } },
        { id: 'c', action: 'expectDisabled', target: { kind: 'id', value: 'save' } },
        { id: 'd', action: 'expectValue', target: { kind: 'id', value: 'email' }, params: { value: 'a@b.c' } },
        { id: 'e', action: 'expectValue', target: { kind: 'id', value: 'phone' }, params: { value: '/\\d{3}/' } },
        {
          id: 'f',
          action: 'expectAttribute',
          target: { kind: 'id', value: 'row' },
          params: { attr: 'aria-checked', value: 'true' },
        },
      ]),
    );
    expect(spec).toContain(`await expect(page.getByTestId("spin").first()).toBeHidden();`);
    expect(spec).toContain(`await expect(page.locator("#save").first()).toBeEnabled();`);
    expect(spec).toContain(`await expect(page.locator("#save").first()).toBeDisabled();`);
    expect(spec).toContain(`await expect(page.locator("#email").first()).toHaveValue("a@b.c");`);
    expect(spec).toContain(`await expect(page.locator("#phone").first()).toHaveValue(new RegExp("\\\\d{3}"));`);
    expect(spec).toContain(`await expect(page.locator("#row").first()).toHaveAttribute("aria-checked", "true");`);
  });

  test('multi-tab automations thread an active-page variable + the context fixture', () => {
    const spec = automationToSpec(
      build([
        { id: 'a', action: 'newTab', params: { url: 'https://example.com/2' } },
        { id: 'b', action: 'click', target: { kind: 'testid', value: 'thing' } },
        { id: 'c', action: 'switchTab', params: { count: 0 } },
        { id: 'd', action: 'closeTab' },
      ]),
    );
    expect(spec).toContain(`async ({ page, context }) => {`);
    expect(spec).toContain(`let active = page;`);
    expect(spec).toContain(`const tab1 = await context.newPage();`);
    expect(spec).toContain(`await tab1.goto("https://example.com/2");`);
    expect(spec).toContain(`active = tab1;`);
    // subsequent locators are rooted at the active page, not `page`
    expect(spec).toContain(`await active.getByTestId("thing").first().click();`);
    expect(spec).toContain(`active = context.pages()[0];`);
    expect(spec).toContain(`await active.close();`);
    expect(spec).toContain(`active = context.pages()[context.pages().length - 1];`);
  });

  test('single-tab automations stay rooted at `page` (no active indirection)', () => {
    const spec = automationToSpec(build([{ id: 'a', action: 'click', target: { kind: 'id', value: 'x' } }]));
    expect(spec).toContain(`async ({ page }) => {`);
    expect(spec).not.toContain(`let active = page;`);
    expect(spec).toContain(`await page.locator("#x").first().click();`);
  });

  test('custom test name override', () => {
    const spec = automationToSpec(build([]), { testName: 'logs in' });
    expect(spec).toContain(`test("logs in", async ({ page }) => {`);
  });

  test('testModule redirects the test/expect import to a consumer fixtures module', () => {
    const spec = automationToSpec(build([]), { testModule: '../fixtures' });
    expect(spec).toContain(`import { expect, test } from "../fixtures";`);
    expect(spec).not.toContain(`from "@playwright/test"`);
  });
});
