/**
 * Git helpers — re-exported from `cwip/node` (their canonical home; the whole
 * surface, including the branch-lifecycle ops and pure parsers, was promoted
 * there from this file). Kept as the entry behind the `rubato/git` public
 * subpath and the import seam for the multi-repo command scripts.
 */

export {
  ageDays,
  aheadBehind,
  aheadBehindRefs,
  type BranchTracking,
  branchCreatedAt,
  branchTracking,
  checkedOutBranches,
  checkout,
  cloneRepo,
  commitAll,
  currentBranch,
  type DiffFile,
  defaultBranch,
  diffNameStatus,
  discardAll,
  discardPaths,
  fetchRemote,
  ffPull,
  ffUpdateBranch,
  fileDiff,
  filterRefs,
  type GitResult,
  type GitTag,
  git,
  gitExcludePatterns,
  goneBranches,
  hasUncommittedChanges,
  isGitRepo,
  type ListTagsOptions,
  listTags,
  localBranches,
  mergedBranches,
  parseBranchNames,
  parseBranchTracking,
  parseCheckedOutBranches,
  parseGoneBranches,
  parseRemoteRefs,
  type RefFilter,
  type RemoteRef,
  refExists,
  remoteBranchSet,
  remoteRefs,
  remoteUrl,
  type ScoredRef,
  scoredRemoteRefs,
  stashCount,
  stashPush,
  statusEntries,
  tagCommit,
} from 'cwip/node';
