/**
 * Orchestration library barrel — the pure parsers, aggregators, and formatters
 * behind the rubato Orchestration page (the area that tracks the unattended
 * "drain the task queue" workflows).
 *
 * Everything here is pure (string/data in, model out — no fs/server/db imports),
 * so it's importable as the `rubato/orchestration` subpath without dragging in the
 * server, and the library-import-boundary guard stays green. The file reads/writes
 * that feed these live in `src/server/orchestration.ts`.
 */

// Re-export the wire types so a `rubato/orchestration` consumer gets the model too.
export type {
  ActiveRun,
  CategoryStat,
  ConfigPatchResult,
  DrainConfig,
  DrainConfigPatch,
  FileLocation,
  FleetPreset,
  FleetSlot,
  FleetTier,
  GroupRollup,
  HistoryEntry,
  LaunchdInfo,
  LogFileInfo,
  LogTail,
  OrchestrationFileDoc,
  OrchestrationFileInfo,
  OrchestrationOverview,
  OrchestrationStats,
  PendingChange,
  Problem,
  ProblemFix,
  ReadyTask,
  RepoStat,
  RestartResult,
  RunEntry,
  RunStatus,
  SaveFleetPreset,
  ThinkingLevel,
  TimingIngestResult,
  TimingOverview,
  TimingQueryParams,
  TimingRow,
  TimingSource,
  TimingSummary,
  TimingTrendPoint,
  UnservableSummary,
  WatchdogAgentResult,
  WatchdogCommand,
  WatchdogCounts,
  WatchdogSnapshot,
  WatchdogStatusLine,
  WatchdogTick,
  WorkerInstance,
  WorkerProcess,
  WorkerSlotStatus,
  WorkflowBoard,
  WorkflowTask,
  WorkflowTaskMeta,
  WorkflowTaskStatus,
} from '../../shared/orchestration';
export {
  bucketTimingTrend,
  fleetPresetId,
  THINKING_LEVELS,
  thinkingTokensFor,
  WORKFLOW_STATUS_LABELS,
  WORKFLOW_STATUSES,
} from '../../shared/orchestration';
export { formatDuration, formatTokens, formatUsd } from './format';
export { parseDurationSeconds, parseHistory } from './parseHistory';
export { parseRunsJsonl, runEntryFromJson, summarizeRunEntries, type WorkerRunStats } from './parseRuns';
export { emptyTaskBoard, parseTaskBoard } from './parseTasks';
export { aggregateStats } from './stats';
export {
  aliasForModelId,
  applyDrainPatch,
  buildWatchdogCommands,
  type CommandPaths,
  changedDrainFields,
  computePending,
  defaultDrainConfig,
  deriveFleetSlots,
  deriveInstances,
  deriveNextRun,
  deriveProblems,
  deriveUnservable,
  effectiveSlots,
  type FleetSlotInput,
  modelLabelForAlias,
  type NextRun,
  needsRestartFieldChanged,
  nextRunIso,
  type ProblemInput,
  parseActiveRun,
  parseDrainConfig,
  parseFleetConfigString,
  parseFleetPresets,
  parseLaunchdPlist,
  parseWatchdogStatus,
  parseWatchdogTick,
  repoFromText,
  type SlotSpec,
  sanitizeFleetTiers,
  serializeDrainConfig,
  serializeFleetPresets,
  setPlistInterval,
  tiersToCoverUnservable,
  upsertFleetPreset,
  type WakeAction,
  wakeAction,
  workerIdFromWorktree,
} from './watchdog';
