import { describe, expect, test } from 'bun:test';
import {
  detectApplication,
  detectScanType,
  detectTotal,
  isAppScanReport,
  parseAppScanReport,
  parseIssueTypes,
  tallySeverities,
} from './parseAppScanReport';

/**
 * Fixtures mirroring the REAL HCL AppScan / ASoC report text layout (validated
 * against sample SAST + DAST PDFs): a "Summary of security issues" block, a
 * `Technology:` field, a "Total security issues:" line, and a "Number of Issues"
 * breakdown table, followed by per-finding blocks with "Severity:" lines.
 */

// SAST: no Critical / Informational in the summary (the real SAST sample omits them);
// includes a page-number "9" right before the "Critical High Medium Low" legend, which
// the looser fallback MUST NOT misread as critical:9.
const SAST = [
  'HCL AppScan Report Report Type: Security Report Scan Name: SAST 2025-07-15 demo.irx Technology: SAST',
  'Report created at: Wednesday, July 16, 2025 This report was generated by HCL AppScan',
  'Summary of security issues High severity issues: 4 Medium severity issues: 2 Low severity issues: 1 Total security issues: 7',
  '9 Critical High Medium Low Informational Summary Total security issues: 7 Issue Types: 3',
  'Number of Issues SQL Injection 4 Cross-Site Scripting 2 Open Redirect 1 2 Issues - By Fix Groups:',
  'How to Fix: SQL Injection Issue 1 of 4 Issue ID: a1 Severity: High Status Open',
  'How to Fix: Cross-Site Scripting Issue 1 of 2 Issue ID: b1 Severity: Medium Status Open',
  'How to Fix: Open Redirect Issue 1 of 1 Issue ID: c1 Severity: Low Status Open',
].join(' ');

// DAST: full 5-severity summary incl. Critical + Informational; keyed off Host; the
// "Number of Issues" table includes a SHA-1 name (embedded digit) + quoted/long names.
const DAST = [
  'HCL AppScan Report Report Type: Security Report Scan Name: Sample Report [mode=demo] Technology: DAST',
  'This report was generated by HCL AppScan',
  'Summary of security issues Critical severity issues: 1 High severity issues: 1 Medium severity issues: 2 Low severity issues: 0 Informational severity issues: 1 Total security issues: 5',
  'Host: demo.testfire.net Port: 443',
  'Issue Types: 4 Number of Issues SQL Injection 1 Cacheable SSL Page Found 2 SHA-1 cipher suites were detected 1 Application Error 1 5 Issues - By Issue Types:',
  'C DAST: SQL Injection 1 How to Fix: SQL Injection Issue 1 of 1 Issue ID: d1 Severity: Critical',
  'M DAST: Cacheable SSL Page Found 2 How to Fix: Cacheable SSL Page Found Issue 1 of 2 Issue ID: d2 Severity: Medium Issue 2 of 2 Issue ID: d3 Severity: Medium',
  'H DAST: SHA-1 cipher suites were detected 1 How to Fix: SHA-1 cipher suites were detected Issue 1 of 1 Issue ID: d4 Severity: High',
  'I DAST: Application Error 1 How to Fix: Application Error Issue 1 of 1 Issue ID: d5 Severity: Informational',
].join(' ');

describe('isAppScanReport', () => {
  test('recognizes ASoC / HCL AppScan markers', () => {
    expect(isAppScanReport('AppScan on Cloud\nHCL AppScan Report')).toBe(true);
    expect(isAppScanReport('Generated by HCL AppScan')).toBe(true);
    expect(isAppScanReport('Some unrelated PDF about invoices')).toBe(false);
  });
});

describe('detectScanType', () => {
  test('from the Technology field, acronyms, or spelled-out phases', () => {
    expect(detectScanType('Technology: SAST')).toBe('SAST');
    expect(detectScanType('Technology: DAST')).toBe('DAST');
    expect(detectScanType('Technology: IAST')).toBe('IAST');
    expect(detectScanType('Scan type: SAST')).toBe('SAST');
    expect(detectScanType('Dynamic Analysis results')).toBe('DAST');
    expect(detectScanType('Software Composition Analysis')).toBe('SCA');
    expect(detectScanType('no technology named')).toBeUndefined();
  });
});

describe('detectApplication', () => {
  test('from common label shapes', () => {
    expect(detectApplication('Application Name: caller-intent-svc')).toBe('caller-intent-svc');
    expect(detectApplication('Application: Billing API')).toBe('Billing API');
  });
  test('DAST keys off the scanned Host', () => {
    expect(detectApplication('Host: demo.testfire.net Port: 443')).toBe('demo.testfire.net');
  });
  test('Scan Name stops before the next labelled field (flattened text)', () => {
    expect(detectApplication('Scan Name: SAST 2025-07-15 demo.irx Technology: SAST Report created at: x')).toBe(
      'SAST 2025-07-15 demo.irx',
    );
  });
});

describe('detectTotal', () => {
  test('reads the explicit "Total security issues" line', () => {
    expect(detectTotal('Total security issues: 105')).toBe(105);
    expect(detectTotal('no total here')).toBeUndefined();
  });
});

describe('tallySeverities — real ASoC summary block (authoritative)', () => {
  test('"<Severity> severity issues: N" wins and ignores the page-number-before-legend trap', () => {
    // SAST omits Critical + Informational; the stray "9" before "Critical High Medium Low"
    // must NOT leak in as critical:9 (the fallback is skipped once the summary matched).
    expect(tallySeverities(SAST)).toEqual({ critical: 0, high: 4, medium: 2, low: 1, informational: 0 });
  });
  test('captures all five severities incl. Critical + Informational (DAST)', () => {
    expect(tallySeverities(DAST)).toEqual({ critical: 1, high: 1, medium: 2, low: 0, informational: 1 });
  });
});

describe('tallySeverities — fallback shapes (no explicit summary block)', () => {
  test('"Critical: 12" label → count form', () => {
    expect(tallySeverities('Critical: 12\nHigh: 5\nMedium: 8\nLow: 3')).toEqual({
      critical: 12,
      high: 5,
      medium: 8,
      low: 3,
      informational: 0,
    });
  });

  test('"12 Critical" count → label form', () => {
    expect(tallySeverities('Findings: 2 Critical, 4 High, 0 Medium, 7 Low')).toEqual({
      critical: 2,
      high: 4,
      medium: 0,
      low: 7,
      informational: 0,
    });
  });

  test('a flattened header row + counts row', () => {
    expect(tallySeverities('Security Issues by Severity\nCritical High Medium Low\n1 9 3 2')).toEqual({
      critical: 1,
      high: 9,
      medium: 3,
      low: 2,
      informational: 0,
    });
  });

  test('missing severities stay 0; the first value wins', () => {
    expect(tallySeverities('Critical 4\n...later... Critical 99 in a per-finding list')).toMatchObject({
      critical: 4,
      high: 0,
    });
  });
});

describe('parseIssueTypes — "Number of Issues" breakdown table', () => {
  test('parses name/count pairs, tolerating digits-in-names (SHA-1) and quoted/long names', () => {
    const types = parseIssueTypes(DAST);
    expect(types.map((t) => ({ name: t.name, count: t.count }))).toEqual([
      { name: 'SQL Injection', count: 1 },
      { name: 'Cacheable SSL Page Found', count: 2 },
      { name: 'SHA-1 cipher suites were detected', count: 1 },
      { name: 'Application Error', count: 1 },
    ]);
    // counts sum to the total — every finding has exactly one issue type
    expect(types.reduce((s, t) => s + t.count, 0)).toBe(5);
  });

  test('best-effort per-type severity from the nearest per-finding Severity line', () => {
    const byName = Object.fromEntries(parseIssueTypes(DAST).map((t) => [t.name, t.severity]));
    expect(byName['SQL Injection']).toBe('critical');
    expect(byName['Cacheable SSL Page Found']).toBe('medium');
    expect(byName['SHA-1 cipher suites were detected']).toBe('high');
    expect(byName['Application Error']).toBe('informational');
  });

  test('no breakdown table → empty array', () => {
    expect(parseIssueTypes('A document with no issue-type table.')).toEqual([]);
  });
});

describe('parseAppScanReport — end to end', () => {
  test('real SAST report shape', () => {
    const out = parseAppScanReport(SAST);
    expect(out.isAppScan).toBe(true);
    expect(out.scanType).toBe('SAST');
    expect(out.severities).toEqual({ critical: 0, high: 4, medium: 2, low: 1, informational: 0 });
    expect(out.total).toBe(7); // the explicit "Total security issues: 7"
    expect(out.issueTypes).toHaveLength(3);
    expect(out.issueTypes.find((t) => t.name === 'SQL Injection')).toMatchObject({ count: 4, severity: 'high' });
  });

  test('real DAST report shape', () => {
    const out = parseAppScanReport(DAST);
    expect(out.scanType).toBe('DAST');
    expect(out.application).toBe('demo.testfire.net');
    expect(out.severities.critical).toBe(1);
    expect(out.severities.informational).toBe(1);
    expect(out.total).toBe(5);
    expect(out.issueTypes).toHaveLength(4);
  });

  test('synthetic label-form report (no explicit summary block) still parses', () => {
    const text = [
      'HCL AppScan Report',
      'AppScan on Cloud',
      'Application Name: caller-intent-svc',
      'Scan Type: SAST',
      'Security Issues by Severity',
      'Critical: 3',
      'High: 11',
      'Medium: 20',
      'Low: 6',
    ].join('\n');
    expect(parseAppScanReport(text)).toEqual({
      isAppScan: true,
      application: 'caller-intent-svc',
      scanType: 'SAST',
      severities: { critical: 3, high: 11, medium: 20, low: 6, informational: 0 },
      issueTypes: [],
      total: 40,
    });
  });

  test('non-AppScan text → isAppScan false, zero totals', () => {
    const out = parseAppScanReport('Just an ordinary document with no security data.');
    expect(out.isAppScan).toBe(false);
    expect(out.total).toBe(0);
    expect(out.scanType).toBeUndefined();
    expect(out.issueTypes).toEqual([]);
  });
});
